- name: 'System OS details'
  fail: msg="Incorrect OS, got {{ansible_distribution}} {{ansible_distribution_major_version}} but expected Debian 10"
  when: (ansible_facts['distribution'] != "Debian" or ansible_facts['distribution_major_version'] != "10")
