sensio_framework_extra:
    router:      { annotations: true } # Deprecated; use routing annotations of Symfony core instead
    request:     { converters: true, auto_convert: true }
    view:        { annotations: true }
    cache:       { annotations: true }
    security:    { annotations: true }
        
