- name: Ensure apache2 is at the latest version
  apt: name=apache2 state=latest

# - name: Start apache2
#   service:
#     name: apache2
#     state: started

- name: Modify date.time zone php.ini apache
  replace:
    dest=/etc/php/7.4/apache2/php.ini
    regexp=';date.timezone ='
    replace='date.time = Europe/Paris'
    backup=yes

- name: Enabled mod_rewrite
  apache2_module: name=rewrite state=present
  notify:
    - restart apache2

- name: create vhost
  template: src=virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}.conf

- name: Remove default apache2 conf
  ansible.builtin.file:
    path: /etc/apache2/sites-available/000-default.conf
    state: absent

- name: a2ensite
  command: a2ensite {{ domain }}.conf
  args:
    creates: /etc/apache2/site-enabled/{{ domain }}.conf
  notify:
    - restart apache2
