#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login:
    path: /api/login

gesdinet_jwt_refresh_token:
  path:       /token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh