- name: Base install
  apt:
    update_cache: yes
    pkg:
      - vim
      - git
      - curl
      - unzip
      - python3

- name: install lsb-release
  apt: name=lsb-release state=present


- name: install ca-certificates
  apt: name=ca-certificates state=present

- name: install apt-transport-https
  apt: name=apt-transport-https state=present

- name: Add an Apt signing key
  apt_key:
      url: https://packages.sury.org/php/apt.gpg
      state: present
      validate_certs: no

- apt_repository:
    repo: deb https://packages.sury.org/php/ buster main
    state: present

- name: Php install
  apt:
    update_cache: yes
    pkg:
      - php7.4
      - php7.4-common
      - php7.4-cli
      - php7.4-dom
      - php7.4-xmlrpc
      - php7.4-mbstring
      - php7.4-intl
      - php7.4-curl
      - php7.4-zip
      - php7.4-mysql

- name: Modify date.time zone php.ini cli
  replace:
    dest=/etc/php/7.4/cli/php.ini
    regexp=';date.timezone ='
    replace='date.time = Europe/Paris'
    backup=yes

- name: install composer
  apt: name=composer state=present
